"""market entities: stock, corporation, sector, region, group

Revision ID: eb9fb7726dd3
Revises: 
Create Date: 2026-05-23 01:05:08.517227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9fb7726dd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ko', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_ko')
    )
    op.create_table('regions',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name_ko', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sectors',
    sa.Column('fics_code', sa.String(length=8), nullable=False),
    sa.Column('name_ko', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('parent_sector_id', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['parent_sector_id'], ['sectors.fics_code'], ),
    sa.PrimaryKeyConstraint('fics_code')
    )
    op.create_table('corporations',
    sa.Column('dart_code', sa.String(length=8), nullable=False),
    sa.Column('name_ko', sa.String(length=256), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('wikidata_qid', sa.String(length=32), nullable=True),
    sa.Column('in_sector_id', sa.String(length=8), nullable=True),
    sa.Column('belongs_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['belongs_to_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['in_sector_id'], ['sectors.fics_code'], ),
    sa.PrimaryKeyConstraint('dart_code')
    )
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name_ko', sa.String(length=256), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('share_class', sa.Enum('common', 'preferred', name='share_class_enum'), nullable=False),
    sa.Column('market', sa.Enum('KOSPI', 'KOSDAQ', 'KONEX', name='market_enum'), nullable=False),
    sa.Column('issued_by_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['corporations.dart_code'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    op.drop_table('corporations')
    op.drop_table('sectors')
    op.drop_table('regions')
    op.drop_table('groups')
    # ### end Alembic commands ###
