"""business structure: report, segment, product, revenue, customer, geographic

Revision ID: bb34bb9167b6
Revises: eb9fb7726dd3
Create Date: 2026-05-23 01:06:54.027378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb34bb9167b6'
down_revision: Union[str, Sequence[str], None] = 'eb9fb7726dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_ko', sa.String(length=256), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_reports',
    sa.Column('dart_rcept_no', sa.String(length=14), nullable=False),
    sa.Column('corporation_id', sa.String(length=8), nullable=False),
    sa.Column('report_type', sa.Enum('사업보고서', '반기보고서', '분기보고서', name='report_type_enum'), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.dart_code'], ),
    sa.PrimaryKeyConstraint('dart_rcept_no')
    )
    op.create_table('business_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corporation_id', sa.String(length=8), nullable=False),
    sa.Column('name_ko', sa.String(length=256), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.dart_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=8), nullable=False),
    sa.Column('buyer_corp_id', sa.String(length=8), nullable=True),
    sa.Column('buyer_raw', sa.String(length=256), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('revenue_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tier', sa.Enum('1차', '2차', 'unknown', name='customer_tier_enum'), nullable=False),
    sa.Column('source_report_id', sa.String(length=14), nullable=False),
    sa.CheckConstraint('(buyer_corp_id IS NOT NULL) OR (buyer_raw IS NOT NULL)', name='cr_buyer_present'),
    sa.ForeignKeyConstraint(['buyer_corp_id'], ['corporations.dart_code'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['corporations.dart_code'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['business_reports.dart_rcept_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geographic_exposures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_corp_id', sa.String(length=8), nullable=True),
    sa.Column('subject_segment_id', sa.String(length=36), nullable=True),
    sa.Column('region_id', sa.String(length=8), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source_report_id', sa.String(length=14), nullable=False),
    sa.CheckConstraint('(subject_corp_id IS NOT NULL) <> (subject_segment_id IS NOT NULL)', name='ge_subject_exactly_one'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.code'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['business_reports.dart_rcept_no'], ),
    sa.ForeignKeyConstraint(['subject_corp_id'], ['corporations.dart_code'], ),
    sa.ForeignKeyConstraint(['subject_segment_id'], ['business_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_compositions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_corp_id', sa.String(length=8), nullable=True),
    sa.Column('subject_segment_id', sa.String(length=36), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('absolute_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source_report_id', sa.String(length=14), nullable=False),
    sa.CheckConstraint('(subject_corp_id IS NOT NULL) <> (subject_segment_id IS NOT NULL)', name='rc_subject_exactly_one'),
    sa.ForeignKeyConstraint(['source_report_id'], ['business_reports.dart_rcept_no'], ),
    sa.ForeignKeyConstraint(['subject_corp_id'], ['corporations.dart_code'], ),
    sa.ForeignKeyConstraint(['subject_segment_id'], ['business_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revenue_compositions')
    op.drop_table('geographic_exposures')
    op.drop_table('customer_relations')
    op.drop_table('business_segments')
    op.drop_table('business_reports')
    op.drop_table('products')
    # ### end Alembic commands ###
